os:
- osx
- linux
before_install:
- [[ "$TRAVIS_OS_NAME" == "osx" ]] && brew update
install:
- [[ "$TRAVIS_OS_NAME" == "osx" ]] && brew install python wxpython
- [[ "$TRAVIS_OS_NAME" == "osx" ]] && pip install py2app
- [[ "$TRAVIS_OS_NAME" == "linux" ]] && pip install py2deb
script:
- make tests
- [[ "$TRAVIS_OS_NAME" == "osx" ]] && make app
- [[ "$TRAVIS_OS_NAME" == "linux" ]] && make deb
- cd dist/
- [[ "$TRAVIS_OS_NAME" == "osx" ]] && zip -r IDFVersionUpdater.zip IDFVersionUpdater.app/
- [[ "$TRAVIS_OS_NAME" == "linux" ]] && zip -r IDFVersionUpdater.deb IDFVersionUpdater.app/
- cd -
deploy:
  provider: releases
  skip_cleanup: true
  file: dist/IDFVersionUpdater.zip
  on:
    tags: true
  api-key:
    secure: Y5BJpXmGlPGvGovo8NFVjHfZYBlkF0LITNgwj1CVAjI0PWTwaKJXEtZ3bDvoRaBvt3K9u/gFVFIxUIEs1azYSUBQpf94Ac1s6q+XUKWpINx66v2iSP4a9N1pacCwBI2l2ho9zskaEEqZF4pP+ScAwWpOYh06tOSKePifQW+Qlvavdd+SZCBlpxl2WQufhBHfigfCKaHc3hFUyUu5pLvoIcPDVjfDQP3tNi3N72zGTCWE4h513QHyXOkJxs2QkCNn7MmXig/oLRtYYB4ryuZxwDjoUU4Fi5AJK6lTsAox0cifnEmuKGwPOIsfW4pfoHTix3a4MyejBDk2p12SYhT0TCytN0+vzyLK2yFfeOj32Ww3VzLk7/s3CL7YQuSafRhw08ktitPdoYCJEXAZuUSrEUVkIPsYOWgh6k5ie7XXs9lSm3EMm5j/MwzjJQ/egGNH69sgy1MsyOBnBRd0i/2jNDg615X9j4ndxlmmOkWzq+OH8EhOXcZw+qbfe1U1UEUAr28iPhthxGjvpCwJlRPPgPcGrJAyDS+2lVnw4bFvc4tu/nmOGj2QL79t1C5KB8D10yvEAkMudIfebVArqJ5v3svovVAf8fKsBoitFjeqMRxTZRlh94ySdkP8vKd5orWwpfbkcDkV6LISHC1RXonSPTUBcggdQ0Se+zKHBIGmUzU=
