name: Flake8

# More of an overall linting workflow since it runs mypy also

on: [push]

jobs:
  flake8:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install Pip Dependencies
      run: pip install flake8 mypy

    - name: Run mypy
      run: mypy energyplus_transition

    - name: Run Flake8
      run: flake8 energyplus_transition
