name: Lint

on: [push]

jobs:
  flake8:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install Pip Dependencies
      run: pip install -e .[test]

    - name: Run isort
      run: isort energyplus_transition tests

    - name: Run black
      run: black energyplus_transition tests

    - name: Run mypy
      run: mypy energyplus_transition tests

    - name: Run Flake8
      run: flake8 energyplus_transition tests
